version: '3.8'

services:
  notebook:
    container_name: notebook
    user: root
    privileged: true
    image: psyoblade/data-engineer-notebook:1.7.5
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    network_mode: host

